name: Build & Test with Bazel
on: [push, pull_request]
jobs:
  build:
    name: bazel build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bazelisk build ...
  test:
    name: bazel test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bazelisk test ...
